from InventoryManagement import InventoryManagement
print("===== INVENTORY QA =====")
i = InventoryManagement()
print("\nTest 1: Stock Availability")
i.add_product("A", "Laptop", 20)
i.remove_product("A", "Laptop", 5)
print("\nTest 2: Insufficient Inventory")
i.remove_product("A", "Laptop", 100)
print("\nTest 3: Warehouse Transfer")
i.transfer_stock("A", "B", "Laptop", 10)
print("\nTest 4: Low Stock Detection")
i.low_stock(15)
print("\nTest 5: Invalid Product")
i.remove_product("A", "Phone", 5)
print("\nTest 6: Negative Inventory")
i.add_product("A", "Mouse", -10)
print("\nTest 7: Multiple Warehouses")
i.add_product("A", "Keyboard", 10)
i.add_product("B", "Keyboard", 30)
i.add_product("C", "Keyboard", 5)
i.select_warehouse("Keyboard", 15)
print("\nFinal Inventory")
i.display()
print("\n===== QA COMPLETED =====")
